name = "AoC"
uuid = "3763443b-930a-4b79-8bbe-32305fa599be"
version = "0.1.0"
authors = ["Alan Liddell <alan.c.liddell@gmail.com>"]

[deps]
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DotEnv = "1.0.0"
HTTP = "1.10.19"
Test = "1.11.0"
julia = "1.6"
